version: "3.7"

services:
  rest-api:
    # build: .
    image: maormor/tienda-dulces:v2
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/tienda_dulces
      spring.datasource.password: pass
      
  carrito-compras: # Pendiente
    image: maormor/carrito-compras:v1
    ports:
      - 8081:80
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PASSWORD: pass
    links:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
      - ./tienda_dulces.sql:/docker-entrypoint-initdb.d/tienda_dulces.sql
#    ports:
#      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: tienda_dulces
